### ISSUE TITLE
[Feature Request] Search for .envrc file in parent of projectile root directory

### ISSUE THREAD

**Issue by favadi** [christianromney/projectile-direnv#2]
It would be us if this package can recursive search until found a `.envrc` in parent directory just like `direnv` command did. If you think it shouldn't be default behaviour, we can add a flag to toggle it.

**Comment by wbolster** [comment]
https://github.com/wbolster/emacs-direnv does that since it uses `direnv` directly.

**Comment by christianromney** [comment]
I've deprecated this package in favor of @wbolster's new package instead. I'll see about getting it pulled from MELPA soon.

**Comment by favadi** [comment]
Thanks @christianromney.
