### ISSUE TITLE
Doesn't work with functions

### ISSUE THREAD

**Issue by cbaines** [christianromney/projectile-direnv#4]
Hey,

Thanks for writing this, and publishing it as free software. I've just got in to using direnv, and I'm really excited about integrating it with Emacs.

I use the `layout_ruby` function in one of my `.envrc` files, but this does not work with projectile-direnv, as it just looks for lines beginning with export.

Would you be open to changing to use `direnv dump` and `direnv apply_dump` to generate the environment changes, which you would then parse, instead of just parsing the `.envrc` file?

Thanks,

Chris

**Comment by wbolster** [comment]
this is exactly what https://github.com/wbolster/emacs-direnv does

**Comment by christianromney** [comment]
@cbaines Thank you for opening this issue, and for using this package. I'm sorry it took so long to respond. I'd like to encourage you to try out the newer package https://github.com/wbolster/emacs-direnv instead, which solves many of the open issues in this package. Best of luck.
