### ISSUE TITLE
Doesn't work with quoted strings

### ISSUE THREAD

**Issue by yamadapc** [christianromney/projectile-direnv#5]
```
export SOMETHING="something"
```

Loads `SOMETHING` as `"something"`, instead of `something`.

**Comment by wbolster** [comment]
https://github.com/wbolster/emacs-direnv uses `direnv export json`, which solves this problem.

**Comment by christianromney** [comment]
@yamadapc Thank you for opening this issue and for using this package. I'm sorry it took so long to respond. I'd like to encourage you to try out the newer package https://github.com/wbolster/emacs-direnv instead, which solves many of the open issues in this package. Best of luck.
