### ISSUE TITLE
relation to emacs-direnv

### ISSUE THREAD

**Issue by wbolster** [christianromney/projectile-direnv#6]
hi,

it seems to me that [emacs-direnv](https://github.com/wbolster/emacs-direnv) does most (all?) of the things that this package does, but in a more generic and flexible way.

is there any use case for this package that is not covered by emacs-direnv?

**Comment by christianromney** [comment]
Hi @wbolster I don't know yet. This package is a year old, and `emacs-direnv` did not exist then. I'll take a look at it, but feel free to try it and let me know if it's better. I'd be quite happy to point to it instead.

**Comment by wbolster** [comment]
well, i wrote the other one. :)

does this package serve any use case not served by my package? if so, it might be worth adding that, hence my question.

**Comment by christianromney** [comment]
Nice work, I've just looked at it and would much prefer using it. There's 1 feature this package has that you could port very easily: reporting which envvars were set. I opened an issue in your repo for this. I also opened a suggested new feature (which this package does not have): unloading envvars. I'd be happy to put a deprecation notice on this package and refer people to yours.

**Comment by wbolster** [comment]
awesome, let's bundle mental effort ;)

**Comment by christianromney** [comment]
@wbolster https://github.com/christianromney/projectile-direnv/blob/develop/README.org#deprecation-notice
